name: bloc_clean_architecture
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  # dartz: ^0.10.1
  connectivity: ^3.0.6
  http: ^0.13.5
  shared_preferences: ^2.0.18
  either_dart: ^0.3.0


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner:

flutter:
  uses-material-design: true