// Mocks generated by Mockito 5.3.2 from annotations
// in bloc_clean_architecture/test/features/domain/use_cases/get_random_trivial_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc_clean_architecture/core/errors/app_error.dart' as _i5;
import 'package:bloc_clean_architecture/features/trivial/domain/entities/trivia_entity.dart'
    as _i6;
import 'package:bloc_clean_architecture/features/trivial/domain/repositories/trivia_repo.dart'
    as _i3;
import 'package:either_dart/either.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TriviaRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockTriviaRepo extends _i1.Mock implements _i3.TriviaRepo {
  MockTriviaRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.TriviaEntity>> getConcreteTrivia(
          int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConcreteTrivia,
          [number],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i6.TriviaEntity>>.value(
                _FakeEither_0<_i5.AppError, _i6.TriviaEntity>(
          this,
          Invocation.method(
            #getConcreteTrivia,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i6.TriviaEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.TriviaEntity>> getRandomTrivia() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomTrivia,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i6.TriviaEntity>>.value(
                _FakeEither_0<_i5.AppError, _i6.TriviaEntity>(
          this,
          Invocation.method(
            #getRandomTrivia,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i6.TriviaEntity>>);
}
