// Mocks generated by Mockito 5.3.2 from annotations
// in bloc_clean_architecture/test/features/domain/use_cases/get_concrete_trivial_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc_clean_architecture/core/errors/app_error.dart' as _i5;
import 'package:bloc_clean_architecture/features/trivial/domain/entities/trivial.dart'
    as _i6;
import 'package:bloc_clean_architecture/features/trivial/domain/repositories/trivial_repo.dart'
    as _i3;
import 'package:either_dart/either.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TrivialRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrivialRepo extends _i1.Mock implements _i3.TrivialRepo {
  MockTrivialRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.TrivialEntity>> getConcreteTrivial(
          int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConcreteTrivial,
          [number],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i6.TrivialEntity>>.value(
                _FakeEither_0<_i5.AppError, _i6.TrivialEntity>(
          this,
          Invocation.method(
            #getConcreteTrivial,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i6.TrivialEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.TrivialEntity>> getRandomTrivial() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomTrivial,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i6.TrivialEntity>>.value(
                _FakeEither_0<_i5.AppError, _i6.TrivialEntity>(
          this,
          Invocation.method(
            #getRandomTrivial,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i6.TrivialEntity>>);
}
